### ISSUE TITLE
Some character are missing in created font

### ISSUE THREAD

**Issue by Detector-I** [maltaisn/msdf-gdx#4]
Hi, thank you for the great tool
I tried to use it to generate some arabic font, but no matter what I try some character are always missing
I create the character list from bmfont character list so Im sure does character actually exist in the font, but for some reason when I create a font with your tool does character are missing...
what could be the problem?

**Comment by maltaisn** [comment]
Can you provide the font file and the configuration used?

**Comment by maltaisn** [comment]
This probably belongs in https://github.com/maltaisn/msdf-gdx-gen

I'll close for lack of details.
